### PR TITLE
enhancement: add type support for exported connect

### PR DESCRIPTION
**Pull request by DeVoresyah**
### `connect({})` type support
Add type support for `connect({})`. It will show suggestion when called inside component / screen

### CODE REVIEW

**Comment by rizbud** [comment]
LGTM!

**Review by rizbud — APPROVED** [review]

**Review by ambrizals — APPROVED** [review]
For suggestion maybe avoid using function to create a new object of class, maybe should be use static method.

**Comment by DeVoresyah** [comment]
> For suggestion maybe avoid using function to create a new object of class, maybe should be use static method.

any example ?

**Comment by DeVoresyah** [comment]
> For suggestion maybe avoid using function to create a new object of class, maybe should be use static method.

I will merge this PR first, later on we can enhance on that

**Pull request merged**
